[package]
name = "miniraw"
version = "1.0.4"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
edition = "2018"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"

[dependencies]
log = { version = "0.4", features = ["std"] }
tokio = { version = "1", features = ["net", "fs", "rt-multi-thread", "io-util", "macros"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
widestring = "0.4"
winapi = { version = "0.3", features = ["libloaderapi", "winuser", "errhandlingapi"] }

[build-dependencies]
embed-resource = "1"
