[package]
name = "miniraw"
version = "1.0.3"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
edition = "2018"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"

[dependencies]
log = { version = "0.4", features = ["std"] }
tokio = { version = "0.2", features = ["tcp", "fs", "rt-threaded", "macros", "stream"] }
futures-util = "0.3"
time = "0.2"
widestring = "0.4"
winapi = { version = "0.3", features = ["libloaderapi", "winuser", "errhandlingapi"] }
