[package]
name = "miniraw"
version = "1.0.2"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
edition = "2018"

[profile.release]
lto = true
opt-level = "z"

[dependencies]
log = { version = "0.4", features = ["std"] }
futures = "0.1"
time = "0.1"
tokio = { version = "0.1", features = ["fs"] }
widestring = "0.4"
winapi = { version = "0.3", features = ["libloaderapi", "winuser", "errhandlingapi"] }
